spring:
  application:
    name: BeautySaloonSystem
  datasource:
    url: jdbc:mysql://localhost:3306/SaloonManagement?createDatabaseIfNotExist=true

    username: root
    password: YOUR PASSWORD


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 3MB
