spring:
  application:
    name: BeautySaloonSystem
  datasource:
    url: jdbc:mysql://localhost:3306/SaloonManagement?createDatabaseIfNotExist=true
    username: root
    password: Vimi#2006

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true